export { default as Header } from "./Header"
export { default as Navigation } from "./Navigation"
export { default as Footer } from "./Footer"
export { default as HomeSectionA } from "./HomeSectionA"
export { default as HomeSectionB } from "./HomeSectionB"
export { default as HomeSectionC } from "./HomeSectionC"
export { default as HomeAbout } from "./HomeAbout"